### ISSUE TITLE
Bug fix: exit code greater than zero results blockquoted Markdown

### ISSUE THREAD

**Issue by gimolai** [reconquest/shdoc#11]
The

```bash
# @exitcode >0 On failure
```

function tag produces:

* >**0**: On failure

instead of:

* **\>0**: On failure

and this is not the desired working.

**Comment by seletskiy** [comment]
@gimolai good point. Can you fix it?

**Comment by gimolai** [comment]
https://github.com/reconquest/shdoc/blob/master/shdoc#L37
```
-    styles["github", "exitcode", "from"] = "([0-9]) (.*)"
+    styles["github", "exitcode", "from"] = "([>!]?[0-9]{1,3}) (.*)"
```
This is that. I have no permission to access the repository, so I can't push it.
