### ISSUE TITLE
[TOC] wrong with functions containing '-'

### ISSUE THREAD

**Issue by rockandska** [reconquest/shdoc#15]
Hi,

I didn't test shdoc yet but it looks like exactly what I'm looking for ^^
From the demo, I observed that some anchor doesn't work. Its seems only hit functions containing '-'.

It is related to this part of code who seems a bit brutal :smile: 
https://github.com/reconquest/shdoc/blob/e334b0291695f624189192e0053636f59fd2bd6f/shdoc#L167

Regards

**Comment by seletskiy** [comment]
@rockandska: can you propose a PR to change this behavior?

**Comment by rockandska** [comment]
@seletskiy : done in #16
