### ISSUE TITLE
It may be some problem of mine but I can't use the script. Any bash file that I pass as a parameter it returns me 3 empty lines.

### ISSUE THREAD

**Issue by ricardosierra** [reconquest/shdoc#18]
Printscreen of my terminal:
https://ibb.co/W3TSJRd

Files used in terminal test:
https://raw.githubusercontent.com/ricardosierra/dotfiles/master/source/50_developer.sh
https://raw.githubusercontent.com/ricardosierra/dotfiles/master/source/50_net.sh
https://github.com/ricardosierra/dotfiles/blob/master/source/50_vcs.sh

I using tmux with zsh!

I apologize if it is a trivial mistake made because of me.

**Comment by kovetskiy** [comment]
Hi! You need to define `@description` to get your comments passed, check out the example from readme:
https://github.com/reconquest/shdoc#function-tags
