### ISSUE TITLE
Update Installation Instructions

### ISSUE THREAD

**Issue by DanielArnett** [reconquest/shdoc#20]
Update the clone line to read

`git clone --recurse-submodules https://github.com/reconcquest/shdoc`

If anyone wants complete instructions for Ubuntu they would be 

```
sudo apt-get update
sudo apt-get install gawk
git clone --recurse-submodules https://github.com/reconcquest/shdoc
cd shdoc
sudo make install
```

**Comment by kovetskiy** [comment]
This should be fixed now, thanks!
