### ISSUE TITLE
anchor messed up when using _ (underscore) in function name  in "see also"

### ISSUE THREAD

**Issue by bash-stack** [reconquest/shdoc#22]
As seen  [Here in the _dedup section](https://b4sh-stack.gitlab.io/librarydoc/#_dedup) 
under "see also" , the function _dedup_sort() gets referenced as URL/**#dedupsort** [Defect Link](https://b4sh-stack.gitlab.io/librarydoc/#dedupsort)
the proper location would have been URL/**#_dedup_sort** [Working Link](https://b4sh-stack.gitlab.io/librarydoc/#_dedup_sort)

Regards

**Comment by tomjn** [comment]
Encountering the same issues here, Jekyll uses underscores for headings, shdoc does not
