### ISSUE TITLE
Regarding hyperlink option non-availability

### ISSUE THREAD

**Issue by mani3029** [reconquest/shdoc#32]
Hi Team,

Currently i am not able to find a way to create hyperlink in generated .md file. If  opened in browser the generated .md file it is all plain .So do we have any option with which we can create hyperlink b/w Index and functions.
Do we have option to create pdf file documentation as well from shdoc itself as well?

Thanks

**Comment by mani3029** [comment]
Hi Team,

Any suggestions ?

Thanks

**Comment by kovetskiy** [comment]
Hello,

* try to put markdown link `[link](link)` into the comments instead of pure links
* shdoc doesn't generate pdf, it only generates markdown, I think you can use some other tools to generate pdf from markdown.

**Comment by mani3029** [comment]
Thanks a lot @kovetskiy for your suggestions .2nd part is clear  regarding 1st one still i have some doubt.

**To be precise below is what i am trying to achieve .**

## Index

* [func_1()](#func_1)
* [func_2()](#func_2)
 * [func_3()](#func_3)


### func_1()

Description of func_1

_Function has no arguments._

#### Exit codes

* **1**: Failure/Error case.

### func_2()

Description of func_2

_Function has no arguments._

#### Exit codes

* **1**: Failure/Error case.

### func_3()

Description of func_3

_Function has no arguments._

#### Exit codes

* **1**: Failure/Error case.

**So While opening in browser can we achieve a functionality where  Index of func_1 becomes hyperlink as well as clicking there will take us to it's function definition.**


Thanks

**Comment by kovetskiy** [comment]
But it's working like that already, no?
Here we have Index with clickable links 
https://github.com/reconquest/shdoc/blob/master/examples/readme-example.md

**Comment by mani3029** [comment]
In case i am opening raw .md file generated by shdoc hyperlink part not working for me .Tried opening .md file in chrome browser in windows 10.
Version details-Version 88.0.4324.150 (Official Build) (64-bit).
Let me know in case i am missing something.

Thanks

**Comment by kovetskiy** [comment]
I'm not sure what you mean by opening markdown in chrome browser. Markdown should be rendered by something into HTML.
