### ISSUE TITLE
@description with indent does not work

### ISSUE THREAD

**Issue by Lonerider2010** [reconquest/shdoc#33]
First of all, thank you for this really useful application. That helps me to document my bash scripts with low effort.
Developing bash scripts with VSCodium and Bash IDE, I am used to indent the functions. That allows me the folding of source text. Using annotations like `@example,` `@arg`, `@exitcode`, and `@see` is no problem, they work fine with indentation. But when I indent the `@description`, it disappears. So please change the handling of `@description`, so that indentation is possible. Thanks.

**Comment by kovetskiy** [comment]
Hi!

I believe this is because of this regexp: https://github.com/reconquest/shdoc/blob/master/shdoc#L321
here is the regexp that is being used for `@example`: https://github.com/reconquest/shdoc/blob/master/shdoc#L344

**Comment by kovetskiy** [comment]
Here is also PR probably solving the issue: https://github.com/reconquest/shdoc/pull/21
But the tests were broken because of that.

**Comment by Lonerider2010** [comment]
@kovetskiy: thanks for the second hint, that helps me. So the only question is how to correct the PR so that it works without broken tests.
