### ISSUE TITLE
Bug fix: allow white space in function decl

### ISSUE THREAD

**Issue by jdarling** [reconquest/shdoc#4]
First, great library, very useful.  Saved me a TON of work building the same :)

When trying to use it on our existing codebase I found a "bug" where if you use whitespace in your function decl's it throws things off due to the pattern you used (line 143/4 depending on your start preference):

``` awk
/^(function )?([a-zA-Z0-9_:-]+)(\(\))? \{/ && docblock != "" {
```

Changing that to the following allows whitespace:

``` awk
/^(function([ \t])+)?([a-zA-Z0-9_:-]+)([ \t]*)(\(([ \t]*)\))?([ \t]*)\{/ && docblock != "" {
```

**Comment by kovetskiy** [comment]
@jdarling can you please create a pull-request for it?

**Comment by jdarling** [comment]
Done in PR #5

**Comment by jas-** [comment]
I have also run into a similar issue where it doesn't pick up the following:
```
function fname
{
```
