### ISSUE TITLE
Add an example of usage in the README

### ISSUE THREAD

**Issue by gwpantazes** [reconquest/shdoc#6]
Can you please add an example/examples of how you call `shdoc` to the README?
> shdoc.awk has no args and expects shell script with comments as described above on the stdin and will markdown output result on the stdout.

Seeing that it takes input via the STDIN with no arguments, I tried a few different things all of which did not work:
```bash
$ cat .bash_profile | shdoc
/usr/bin/awk: calling undefined function gensub
 input record number 5, file 
 source line number 47
$ shdoc .bash_profile     # I knew this one wouldn't work...
/usr/bin/awk: calling undefined function gensub
 input record number 5, file .bash_profile
 source line number 47
$ shdoc << .bash_profile
>                                             # I hit ^C to get out of this
$ shdoc <<< .bash_profile



# Empty space printed ^^^
$ $ shdoc <<< cat .bash_profile
/usr/bin/awk: calling undefined function gensub
 input record number 5, file .bash_profile
 source line number 47
$ shdoc <<< $(cat .bash_profile)


# Empty space printed ^^^
```

I'm not having any luck with trying things out / Googling for how to provide STDIN to a script. I'm no bash expert, but I'd love to use your project! So could you please provide some explicit calls you use to use `shdoc`?

**Comment by kovetskiy** [comment]
https://github.com/reconquest/tests.sh/blob/master/Makefile#L1-L2

**Comment by meatware** [comment]
cheers mate!
